# Generated by Django 4.2.4 on 2023-08-27 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='created',
        ),
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
