# Generated by Django 4.2.4 on 2023-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, blank=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('content', models.TextField(max_length=1000)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
